name: Deploy

on:
  push:
    branches: ["main", "fixup-deploy-action"]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: build
        run: |
          ./build.sh
      - name: setup-ssh
        env:
          SSH_HOST_PUB_KEY: ${{ secrets.SSH_HOST_PUB_KEY }}
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          install -m 0600 -D /dev/null ~/.ssh/deploy_key
          echo $SSH_DEPLOY_KEY > ~/.ssh/deploy_key
          echo $SSH_HOST_PUB_KEY >> ~/.ssh/known_hosts
      - name: deploy
        env:
          SSH_ARGS: "-i ~/.ssh/deploy_key"
        run: |
          ./deploy.sh



