name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          ./build.sh
      - name: setup-ssh
        env:
          SSH_HOST_PUB_KEY: ${{ secrets.SSH_HOST_PUB_KEY }}
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          echo $SSH_HOST_PUB_KEY >> ~/.ssh/known_hosts
          install -m 0600 -D /dev/null ~/.ssh/deploy_key
          echo $SSH_DEPLOY_KEY > ~/.ssh/deploy_key
      - name: deploy
        env:
          SSH_ARGS: "-i $HOME/.ssh/deploy_key"
        run: |
          ./deploy.sh



